[install]
# Equivalent to pnpm's onlyBuiltDependencies
trustedDependencies = [
  "@parcel/watcher",
  "@swc/core", 
  "edgedriver",
  "esbuild",
  "geckodriver",
  "unrs-resolver"
]

[install.lockfile]
# Use frozen lockfile equivalent
frozen = true
