contact_links:
  - name: GitHub Community Support
    url: https://github.com/devhau/gsc-bulk-remover/discussions
    about: Please leave your questions here or on Discord - Link below "Security Bug Bounty"
  - name: GitHub Security Bug Bounty
    url: https://discord.gg/RhETcmdW
    about: Please report security vulnerabilities here(Send DM to devhau or tell us on chat, you want to report it).
